// Generates js/data/preflop.js — the 169 No-Limit Hold'em starting hands with
// their strength and the ordering that percentage ranges ("top 22%") cut from.
//
// Run with: npm run gen
//
// Ordering a hand by its all-in equity against a random hand alone is wrong in a
// way that shows up immediately: it puts TT above AKs and 88 above ATs, because
// medium pairs beat junk often while doing badly against anything that raises.
// So each hand is measured twice — against a random hand (the loose multiway
// pot) and against a strong range (the hand that just raised into you) — and
// the two are averaged, then nudged by playability premiums for hands that flop
// well relative to their showdown equity.

import { writeFileSync } from 'node:fs';
import { allHandCodes, combosOf, rankIndex } from '../js/cards.js';
import { evaluate } from '../js/evaluator.js';
import { mulberry32 } from '../js/rng.js';

const TRIALS = 60000;
const STRONG_RANGE_SHARE = 0.15;

/** Equity of `code` against one opponent drawn from `opponentCombos` (null = any hand). */
function measure(code, seed, opponentCombos) {
  const combos = combosOf(code);
  const rng = mulberry32(seed);
  const used = new Uint8Array(52);
  const seven = new Int32Array(7);
  const board = new Int32Array(5);
  let points = 0;
  let played = 0;

  for (let t = 0; t < TRIALS; t++) {
    used.fill(0);
    const hero = combos[(rng() * combos.length) | 0];
    used[hero[0]] = 1;
    used[hero[1]] = 1;

    let villain;
    if (opponentCombos) {
      villain = null;
      for (let attempt = 0; attempt < 100; attempt++) {
        const pick = opponentCombos[(rng() * opponentCombos.length) | 0];
        if (used[pick[0]] || used[pick[1]]) continue;
        villain = pick;
        break;
      }
      if (!villain) continue;
    } else {
      villain = [0, 0];
      for (let i = 0; i < 2; i++) {
        let c;
        do {
          c = (rng() * 52) | 0;
        } while (used[c]);
        used[c] = 1;
        villain[i] = c;
      }
    }
    used[villain[0]] = 1;
    used[villain[1]] = 1;

    for (let i = 0; i < 5; i++) {
      let c;
      do {
        c = (rng() * 52) | 0;
      } while (used[c]);
      used[c] = 1;
      board[i] = c;
    }
    for (let i = 0; i < 5; i++) seven[2 + i] = board[i];

    seven[0] = hero[0];
    seven[1] = hero[1];
    const h = evaluate(seven, 7);
    seven[0] = villain[0];
    seven[1] = villain[1];
    const v = evaluate(seven, 7);
    points += h > v ? 1 : h === v ? 0.5 : 0;
    played++;
  }
  return points / played;
}

// Playability premiums, in equity points, on top of measured strength.
const SUITED_BONUS = 0.03;
const GAP_BONUS = [0.02, 0.012, 0.006, 0.002]; // connector, one-gap, two-gap, three-gap
const BROADWAY_BONUS = 0.008; // both cards ten or better
const SET_MINE_PENALTY = 0.022; // 66 and below only realise equity when they hit

function playability(code) {
  const hi = rankIndex(code[0]);
  const lo = rankIndex(code[1]);
  if (hi === lo) return hi <= 4 ? -SET_MINE_PENALTY : 0;
  let bonus = code[2] === 's' ? SUITED_BONUS : 0;
  const gap = hi - lo - 1;
  if (gap < GAP_BONUS.length) bonus += GAP_BONUS[gap];
  if (lo >= 8) bonus += BROADWAY_BONUS;
  return bonus;
}

const codes = allHandCodes();

// Pass one: strength against a random hand, which bootstraps a strong range.
const vsRandom = new Map(codes.map((code, i) => [code, measure(code, 1000 + i, null)]));
const bootstrap = [...codes].sort((a, b) => vsRandom.get(b) + playability(b) - (vsRandom.get(a) + playability(a)));

const strongCombos = [];
let covered = 0;
for (const code of bootstrap) {
  if (covered / 1326 >= STRONG_RANGE_SHARE) break;
  const combos = combosOf(code);
  strongCombos.push(...combos);
  covered += combos.length;
}

// Pass two: strength against that strong range.
const vsStrong = new Map(codes.map((code, i) => [code, measure(code, 5000 + i, strongCombos)]));

const rows = codes.map((code) => {
  const strength = vsRandom.get(code);
  const blended = 0.5 * strength + 0.5 * vsStrong.get(code);
  return { code, strength, vsStrong: vsStrong.get(code), rank: blended + playability(code) };
});
rows.sort((a, b) => b.rank - a.rank);

let cumulative = 0;
const out = rows.map((row) => {
  const combos = row.code.length === 2 ? 6 : row.code[2] === 's' ? 4 : 12;
  cumulative += combos;
  const round = (n) => Math.round(n * 1e4) / 1e4;
  return {
    code: row.code,
    strength: round(row.strength),
    vsStrong: round(row.vsStrong),
    cutoff: round(cumulative / 1326),
  };
});

const map = (key) => JSON.stringify(Object.fromEntries(out.map((r) => [r.code, r[key]])));
const body = `// GENERATED by tools/gen-preflop.mjs — do not edit by hand. Run \`npm run gen\`.
//
// PREFLOP_ORDER runs strongest to weakest.
// HAND_STRENGTH is equity against one random hand.
// STRENGTH_VS_STRONG is equity against a top-15% range.
// RANGE_CUTOFF is the share of all 1326 combos covered once this hand is in, so
// "top 15%" is every hand whose cutoff is at or just past 0.15.

export const PREFLOP_ORDER = ${JSON.stringify(out.map((r) => r.code))};

export const HAND_STRENGTH = ${map('strength')};

export const STRENGTH_VS_STRONG = ${map('vsStrong')};

export const RANGE_CUTOFF = ${map('cutoff')};
`;

writeFileSync(new URL('../js/data/preflop.js', import.meta.url), body);
console.log('top 40:', out.slice(0, 40).map((r) => r.code).join(' '));
console.log('  15%:', out.filter((r) => r.cutoff <= 0.15).map((r) => r.code).join(' '));
console.log('bottom 8:', out.slice(-8).map((r) => r.code).join(' '));
console.log(`wrote ${out.length} hands to js/data/preflop.js`);
